# Generated by Django 2.2.16 on 2022-02-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(help_text='Автор обзора', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор обзора'),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.ForeignKey(help_text='Оцениваемое произведение', on_delete=django.db.models.deletion.CASCADE, related_name='review_titles', to='reviews.Title'),
        ),
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AddField(
            model_name='comments',
            name='review_id',
            field=models.ForeignKey(help_text='Комментарий к обзору', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='reviews.Review'),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_name_year'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='only_one_review_on_autor'),
        ),
    ]
