# Generated by Django 2.2.16 on 2022-02-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220223_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('pk',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
